### ISSUE TITLE
Unable to launch motor controller

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/rd2#3]
From freshly recompiled CMake 3.5.2, YARP 2.3.72.1 w/ opencv_grabber and asrob-uc3m/yarp-devices:

```
pi@raspberrypi ~ $ sudo yarpdev --from /usr/local/share/robotDevastation-robots/contexts/launch/launchRobot.ini
[ERROR]YARP network not available, check if yarp server is reachable
```

YARP network *is* available and I can launch test_grabber, for instance. Looks like this error [originates upstream](https://github.com/robotology/yarp/blob/v2.3.72.1/src/libYARP_dev/src/Drivers.cpp#L485-L491), not in our own code. Any ideas?

PS I had to start YARP's name server on my PC with `yarpserver --ip 222.1.1.92 --write` since Docker's networking was being picked as the first option (both were apparently reported as available, but `yarp name list` was showing the Docker one, only).

**Comment by jgvictores** [comment]
`sudo` sometimes grabs different environmental variables. From [here](https://github.com/asrob-uc3m/robotDevastation-robots/blob/c28eac507402dd85493f0bad9c5c3d627dc07461/scripts/etc/service/launchRobot/run#L3) we see the one that really matters is setting `YARP_CONF`.

**Comment by jgvictores** [comment]
PS: Docker??? (that could also affect #2)

**Comment by PeterBowman** [comment]
Same error today, I didn't have to use `--ip`.

**Comment by jgvictores** [comment]
What is the output of `sudo yarp where`?

**Comment by PeterBowman** [comment]
Can't tell now, but I recall that plain `yarp where` gave the expected output (remote nameserver).

**Comment by jgvictores** [comment]
Yes, that's why I'm concerned about the output using `sudo`.

**Comment by jgvictores** [comment]
Ideas for testing:
1. All yarp detect etc in a `sudo su` so env variables are shared and yarp conf is in `/root`
1. There was a way to `chmod /dev/mem/something` to avoid need of sudo. I guess an udev rule could be set up. However, seems dangerous. 

Anyway, once we get back to the script to which I pointed above (via daemontools) there will be no need for sudo.

**Comment by jgvictores** [comment]
PS: Sorry, cold fingers closed the issue, reopened. : )

**Comment by jgvictores** [comment]
PS2: I've updated https://github.com/asrob-uc3m/robotDevastation-developer-manual/tree/master/robots#configure-yarp-devices-as-services-on-raspi as a result of https://github.com/asrob-uc3m/robotDevastation-developer-manual/issues/12

**Comment by PeterBowman** [comment]
```
$ yarp where
Looking for name server on 222.1.1.92, port number 10000
If there is a long delay, try:
  yarp conf --clean
Name server /root is available at ip 222.1.1.92 port 10000
```

```
$ sudo yarp where
Looking for name server on 222.1.1.26, port number 10000
If there is a long delay, try:
  yarp conf --clean

=======================================================================
==
== PROBLEM
== No valid YARP name server is available.
== Here is the expected configuration:
==   host: 222.1.1.26 port number: 10000
==   namespace: /root
==   type of name server: yarp
== But such a name server was not found.
[...]
```

You were right:

```
$ yarp conf
/home/pi/.config/yarp/yarp.conf
```

```
$ sudo yarp conf
/root/.config/yarp/yarp.conf
```

**Comment by PeterBowman** [comment]
It worked after I replaced `YARP_CONF` with `YARP_CONFIG_HOME` [here](https://github.com/asrob-uc3m/robotDevastation-robots/blob/b21de5b6c4b81c0f1f19c91a1fc3e25a0fd2caca/scripts/etc/service/launchRobot/run#L3) ([ref](http://www.yarp.it/yarp_env_variables.html)). Same for the camera device.

@jgvictores any compelling reason for not marking that as the final solution?

**Comment by jgvictores** [comment]
Oh, yes! We had to do something similar for TEO here: https://github.com/roboticslab-uc3m/teo-developer-manual/commit/2b79bde7890d48f7daf68437b62caa83b89961c3
